import type { Metadata } from "next";
import Sidebar from "@/app/components/Sidebar";
import { ThemeSwitcherProvider } from "./components/ThemeSwitcher";
import { DM_Sans, Sniglet } from "next/font/google";
import "./globals.css";


/* Old Original Fonts

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

*/

// New Fonts
const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const sniglet = Sniglet ({
  variable: "--font-sniglet-var",
  subsets: ["latin"],
  weight: ["400", "800"],
});


export const metadata: Metadata = {
  title: "Daniil Klimenko",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      data-theme={"dark"}
      className={`${dmSans.variable} ${sniglet.variable} h-full antialiased`} // Passing Fonts
    >
      <body className="min-h-full flex flex-col">
        <ThemeSwitcherProvider>
          <Sidebar />
          {children}
        </ThemeSwitcherProvider>
      </body>
    </html>
  );
}
